### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by 0bimaster** [bleakvin/hass-guacamole#1]
Hi bleakvin,

I've stumbled upon your add-on and love the idea of it, unfortunately I can't launch/use it. After installation it keeps showing "exec format error" in the log and the Web UI can't be accessed.

I'm running hass.io (Supervisor version 235 | HassOs version 4.12 (prod) | HomeAssistant version 0.114.3) on a Raspberry Pi 4 (4GB)

Log:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-defaults.sh: executing... 
exec: fatal: unable to exec sh: Exec format error
[cont-init.d] 30-defaults.sh: exited 111.
[cont-init.d] 40-postgres.sh: executing... 
exec: fatal: unable to exec sh: Exec format error
[cont-init.d] 40-postgres.sh: exited 111.
[cont-init.d] 50-extensions: executing... 
exec: fatal: unable to exec sh: Exec format error
[cont-init.d] 50-extensions: exited 111.
[cont-init.d] done.
[services.d] starting services
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
[services.d] done.
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error
exec: fatal: unable to exec sh: Exec format error

Any idea how to fix this?

br,
0bi

**Comment by tux240** [comment]
Hi, I have the same....

**Comment by d-two** [comment]
The Addon is only amd64 compatible!!

![Repos](https://user-images.githubusercontent.com/32079446/96930851-a8015980-14bc-11eb-9e63-829ae9ce1505.PNG)

I forked the Repo and add the ARCH armhf, aarch64 and armv7...

Look at this:

https://community.home-assistant.io/t/new-addon-access-machines-in-your-homenet-with-apache-guacamole-ingress-support/209829/9?u=d-two

**Comment by bleakvin** [comment]
I just changed the addon to use the underlying architecture that @d-two implemented.
