### ISSUE TITLE
Option to expose docker

### ISSUE THREAD

**Issue by rick00001** [bleakvin/hass-guacamole#2]
Hi,
i really like you're addon, i was already using guacamole, but using it as an hassio addon makes maintenance more easy.
the one and only thing i am missing, is the option to expose the container on certain port, so i can use it with a proxy.

Could you add this feature? I think you can look how it needs to be done from one of your forks: d-two / hass-guacamole

Many thanks in advance!

**Comment by bleakvin** [comment]
Hi,
just implemented that. Although you might choose to still use the Addon from d-two i think he might have a little more know how than me.
